import { StyleSheet } from 'react-native';
import { fontFamilies } from '@/theme/typography';

export const styles = StyleSheet.create({
  badge: {
    alignItems: 'center',
    backgroundColor: '#fef3c7',
    borderRadius: 12,
    flexDirection: 'row',
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 4,
  },
  badgeText: { color: '#b45309', fontFamily: fontFamilies.primary.text, fontSize: 12, fontWeight: '600' },
  completedContainer: {
    alignItems: 'center',
    backgroundColor: '#ecfdf5',
    borderRadius: 16,
    marginHorizontal: 16,
    marginVertical: 8,
    padding: 20,
  },
  completedEmoji: { fontSize: 36, marginBottom: 8 },
  completedSubtitle: { color: '#059669', fontFamily: fontFamilies.primary.text, fontSize: 14 },
  completedTitle: {
    color: '#065f46',
    fontFamily: fontFamilies.primary.text,
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 4,
  },
  container: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    elevation: 3,
    marginHorizontal: 16,
    marginVertical: 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.08,
    shadowRadius: 8,
  },
  content: { padding: 16 },
  glow: {
    backgroundColor: '#f59e0b',
    height: 4,
    left: 0,
    position: 'absolute',
    right: 0,
    top: 0,
  },
  habitHint: { color: '#a8a29e', fontFamily: fontFamilies.primary.text, fontSize: 13 },
  habitIcon: { fontSize: 32 },
  habitInfo: { flex: 1 },
  habitName: {
    color: '#1c1917',
    fontFamily: fontFamilies.primary.text,
    fontSize: 17,
    fontWeight: '600',
    marginBottom: 2,
  },
  habitRow: { alignItems: 'center', flexDirection: 'row', gap: 12 },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  progress: { color: '#a8a29e', fontFamily: fontFamilies.primary.text, fontSize: 13, fontWeight: '500' },
});
