/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";
import type * as affirmations_aiParser from "../affirmations/aiParser.js";
import type * as affirmations_aiPrompt from "../affirmations/aiPrompt.js";
import type * as affirmations_index from "../affirmations/index.js";
import type * as affirmations_returnTypes from "../affirmations/returnTypes.js";
import type * as affirmations_types from "../affirmations/types.js";
import type * as affirmations_validators from "../affirmations/validators.js";
import type * as affirmations from "../affirmations.js";
import type * as affirmationsAI from "../affirmationsAI.js";
import type * as affirmationsCRUD from "../affirmationsCRUD.js";
import type * as affirmationsSchedule from "../affirmationsSchedule.js";
import type * as affirmationsScheduleMutations from "../affirmationsScheduleMutations.js";
import type * as affirmationsScheduleQueries from "../affirmationsScheduleQueries.js";
import type * as analytics_helpers from "../analytics/helpers.js";
import type * as analytics_index from "../analytics/index.js";
import type * as analytics_streakHelpers from "../analytics/streakHelpers.js";
import type * as analytics_types from "../analytics/types.js";
import type * as analytics_weeklyHelpers from "../analytics/weeklyHelpers.js";
import type * as analytics from "../analytics.js";
import type * as analyticsCompliance from "../analyticsCompliance.js";
import type * as analyticsDistribution from "../analyticsDistribution.js";
import type * as analyticsOverview from "../analyticsOverview.js";
import type * as analyticsTrend from "../analyticsTrend.js";
import type * as analyticsWeekly from "../analyticsWeekly.js";
import type * as articles from "../articles.js";
import type * as auth from "../auth.js";
import type * as categories from "../categories.js";
import type * as character_attributes from "../character/attributes.js";
import type * as character_calculations from "../character/calculations.js";
import type * as character_getCharacterStats from "../character/getCharacterStats.js";
import type * as character_index from "../character/index.js";
import type * as character_types from "../character/types.js";
import type * as character from "../character.js";
import type * as debugHabitStrength from "../debugHabitStrength.js";
import type * as diagnose from "../diagnose.js";
import type * as habitStrength_allHabitsStats from "../habitStrength/allHabitsStats.js";
import type * as habitStrength_compliance from "../habitStrength/compliance.js";
import type * as habitStrength_constants from "../habitStrength/constants.js";
import type * as habitStrength_dateUtils from "../habitStrength/dateUtils.js";
import type * as habitStrength_getStrengthInfo from "../habitStrength/getStrengthInfo.js";
import type * as habitStrength_legacyFormula from "../habitStrength/legacyFormula.js";
import type * as habitStrength_logistic from "../habitStrength/logistic.js";
import type * as habitStrength_momentum from "../habitStrength/momentum.js";
import type * as habitStrength_recalculate from "../habitStrength/recalculate.js";
import type * as habitStrength_snapshot from "../habitStrength/snapshot.js";
import type * as habitStrength_strengthLevel from "../habitStrength/strengthLevel.js";
import type * as habitStrength_types from "../habitStrength/types.js";
import type * as habitStrength_updateParams from "../habitStrength/updateParams.js";
import type * as habitStrength_updateStrength from "../habitStrength/updateStrength.js";
import type * as habitStrength from "../habitStrength.js";
import type * as habits_archive from "../habits/archive.js";
import type * as habits_create from "../habits/create.js";
import type * as habits_get from "../habits/get.js";
import type * as habits_getTracking from "../habits/getTracking.js";
import type * as habits_list from "../habits/list.js";
import type * as habits_pause from "../habits/pause.js";
import type * as habits_remove from "../habits/remove.js";
import type * as habits_reorder from "../habits/reorder.js";
import type * as habits_stats from "../habits/stats.js";
import type * as habits_toggle from "../habits/toggle.js";
import type * as habits_types from "../habits/types.js";
import type * as habits_update from "../habits/update.js";
import type * as habits_utils from "../habits/utils.js";
import type * as habits_validation from "../habits/validation.js";
import type * as habits_validators from "../habits/validators.js";
import type * as habits from "../habits.js";
import type * as http from "../http.js";
import type * as initializeAllHabitsStrength from "../initializeAllHabitsStrength.js";
import type * as letters_constants from "../letters/constants.js";
import type * as letters_index from "../letters/index.js";
import type * as letters_types from "../letters/types.js";
import type * as letters from "../letters.js";
import type * as lettersMutations from "../lettersMutations.js";
import type * as lettersQueries from "../lettersQueries.js";
import type * as lettersQueriesExtra from "../lettersQueriesExtra.js";
import type * as lib_inputValidation from "../lib/inputValidation.js";
import type * as migrateHabitsToUser from "../migrateHabitsToUser.js";
import type * as migration from "../migration.js";
import type * as notes_index from "../notes/index.js";
import type * as notes_types from "../notes/types.js";
import type * as notes from "../notes.js";
import type * as notesMutations from "../notesMutations.js";
import type * as notesQueries from "../notesQueries.js";
import type * as predictions_dayPredictions from "../predictions/dayPredictions.js";
import type * as predictions_helpers from "../predictions/helpers.js";
import type * as predictions_index from "../predictions/index.js";
import type * as predictions_suggestions from "../predictions/suggestions.js";
import type * as predictions_types from "../predictions/types.js";
import type * as predictions from "../predictions.js";
import type * as predictions7Day from "../predictions7Day.js";
import type * as predictionsAtRisk from "../predictionsAtRisk.js";
import type * as quickFix from "../quickFix.js";
import type * as recalculateAllHabitsStrength from "../recalculateAllHabitsStrength.js";
import type * as reflections_index from "../reflections/index.js";
import type * as reflections_types from "../reflections/types.js";
import type * as reflections from "../reflections.js";
import type * as reflectionsMutations from "../reflectionsMutations.js";
import type * as reflectionsQueries from "../reflectionsQueries.js";
import type * as router from "../router.js";
import type * as settings_normalizers from "../settings/normalizers.js";
import type * as settings_settings from "../settings/settings.js";
import type * as settings_types from "../settings/types.js";
import type * as settings_validators from "../settings/validators.js";
import type * as settings from "../settings.js";
import type * as storage from "../storage.js";
import type * as streakUtils_dateHelpers from "../streakUtils/dateHelpers.js";
import type * as streakUtils_historyCalculation from "../streakUtils/historyCalculation.js";
import type * as streakUtils_index from "../streakUtils/index.js";
import type * as streakUtils_types from "../streakUtils/types.js";
import type * as streakUtils_updateStreak from "../streakUtils/updateStreak.js";
import type * as streakUtils from "../streakUtils.js";
import type * as subscriptions_helpers from "../subscriptions/helpers.js";
import type * as subscriptions from "../subscriptions.js";
import type * as templates_clearAndDedupe from "../templates/clearAndDedupe.js";
import type * as templates_helpers from "../templates/helpers.js";
import type * as templates_importTemplate from "../templates/importTemplate.js";
import type * as templates_queries from "../templates/queries.js";
import type * as templates_types from "../templates/types.js";
import type * as templates_updateLinks from "../templates/updateLinks.js";
import type * as templates from "../templates.js";
import type * as templatesDataSeed from "../templatesDataSeed.js";
import type * as testStrength from "../testStrength.js";
import type * as tracking_getCompletionStatus from "../tracking/getCompletionStatus.js";
import type * as tracking_helpers from "../tracking/helpers.js";
import type * as tracking_index from "../tracking/index.js";
import type * as tracking_strengthUpdater from "../tracking/strengthUpdater.js";
import type * as tracking from "../tracking.js";
import type * as users from "../users.js";
import type * as visionBoard from "../visionBoard.js";
import type * as visionBoardImages_constants from "../visionBoardImages/constants.js";
import type * as visionBoardImages_helpers from "../visionBoardImages/helpers.js";
import type * as visionBoardImages_index from "../visionBoardImages/index.js";
import type * as visionBoardImages_validators from "../visionBoardImages/validators.js";
import type * as visionBoardImages from "../visionBoardImages.js";
import type * as visionBoardImagesCreate from "../visionBoardImagesCreate.js";
import type * as visionBoardImagesDelete from "../visionBoardImagesDelete.js";
import type * as visionBoardImagesMutations from "../visionBoardImagesMutations.js";
import type * as visionBoardImagesQueries from "../visionBoardImagesQueries.js";
import type * as voiceNotes_index from "../voiceNotes/index.js";
import type * as voiceNotes_streakHelpers from "../voiceNotes/streakHelpers.js";
import type * as voiceNotes_types from "../voiceNotes/types.js";
import type * as voiceNotes from "../voiceNotes.js";
import type * as voiceNotesMutations from "../voiceNotesMutations.js";
import type * as voiceNotesQueries from "../voiceNotesQueries.js";
import type * as voiceNotesStreakQuery from "../voiceNotesStreakQuery.js";
import type * as webhooks_revenuecat from "../webhooks/revenuecat.js";
import type * as webhooks_revenuecatSignature from "../webhooks/revenuecatSignature.js";

/**
 * A utility for referencing Convex functions in your app's API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
declare const fullApi: ApiFromModules<{
  "affirmations/aiParser": typeof affirmations_aiParser;
  "affirmations/aiPrompt": typeof affirmations_aiPrompt;
  "affirmations/index": typeof affirmations_index;
  "affirmations/returnTypes": typeof affirmations_returnTypes;
  "affirmations/types": typeof affirmations_types;
  "affirmations/validators": typeof affirmations_validators;
  affirmations: typeof affirmations;
  affirmationsAI: typeof affirmationsAI;
  affirmationsCRUD: typeof affirmationsCRUD;
  affirmationsSchedule: typeof affirmationsSchedule;
  affirmationsScheduleMutations: typeof affirmationsScheduleMutations;
  affirmationsScheduleQueries: typeof affirmationsScheduleQueries;
  "analytics/helpers": typeof analytics_helpers;
  "analytics/index": typeof analytics_index;
  "analytics/streakHelpers": typeof analytics_streakHelpers;
  "analytics/types": typeof analytics_types;
  "analytics/weeklyHelpers": typeof analytics_weeklyHelpers;
  analytics: typeof analytics;
  analyticsCompliance: typeof analyticsCompliance;
  analyticsDistribution: typeof analyticsDistribution;
  analyticsOverview: typeof analyticsOverview;
  analyticsTrend: typeof analyticsTrend;
  analyticsWeekly: typeof analyticsWeekly;
  articles: typeof articles;
  auth: typeof auth;
  categories: typeof categories;
  "character/attributes": typeof character_attributes;
  "character/calculations": typeof character_calculations;
  "character/getCharacterStats": typeof character_getCharacterStats;
  "character/index": typeof character_index;
  "character/types": typeof character_types;
  character: typeof character;
  debugHabitStrength: typeof debugHabitStrength;
  diagnose: typeof diagnose;
  "habitStrength/allHabitsStats": typeof habitStrength_allHabitsStats;
  "habitStrength/compliance": typeof habitStrength_compliance;
  "habitStrength/constants": typeof habitStrength_constants;
  "habitStrength/dateUtils": typeof habitStrength_dateUtils;
  "habitStrength/getStrengthInfo": typeof habitStrength_getStrengthInfo;
  "habitStrength/legacyFormula": typeof habitStrength_legacyFormula;
  "habitStrength/logistic": typeof habitStrength_logistic;
  "habitStrength/momentum": typeof habitStrength_momentum;
  "habitStrength/recalculate": typeof habitStrength_recalculate;
  "habitStrength/snapshot": typeof habitStrength_snapshot;
  "habitStrength/strengthLevel": typeof habitStrength_strengthLevel;
  "habitStrength/types": typeof habitStrength_types;
  "habitStrength/updateParams": typeof habitStrength_updateParams;
  "habitStrength/updateStrength": typeof habitStrength_updateStrength;
  habitStrength: typeof habitStrength;
  "habits/archive": typeof habits_archive;
  "habits/create": typeof habits_create;
  "habits/get": typeof habits_get;
  "habits/getTracking": typeof habits_getTracking;
  "habits/list": typeof habits_list;
  "habits/pause": typeof habits_pause;
  "habits/remove": typeof habits_remove;
  "habits/reorder": typeof habits_reorder;
  "habits/stats": typeof habits_stats;
  "habits/toggle": typeof habits_toggle;
  "habits/types": typeof habits_types;
  "habits/update": typeof habits_update;
  "habits/utils": typeof habits_utils;
  "habits/validation": typeof habits_validation;
  "habits/validators": typeof habits_validators;
  habits: typeof habits;
  http: typeof http;
  initializeAllHabitsStrength: typeof initializeAllHabitsStrength;
  "letters/constants": typeof letters_constants;
  "letters/index": typeof letters_index;
  "letters/types": typeof letters_types;
  letters: typeof letters;
  lettersMutations: typeof lettersMutations;
  lettersQueries: typeof lettersQueries;
  lettersQueriesExtra: typeof lettersQueriesExtra;
  "lib/inputValidation": typeof lib_inputValidation;
  migrateHabitsToUser: typeof migrateHabitsToUser;
  migration: typeof migration;
  "notes/index": typeof notes_index;
  "notes/types": typeof notes_types;
  notes: typeof notes;
  notesMutations: typeof notesMutations;
  notesQueries: typeof notesQueries;
  "predictions/dayPredictions": typeof predictions_dayPredictions;
  "predictions/helpers": typeof predictions_helpers;
  "predictions/index": typeof predictions_index;
  "predictions/suggestions": typeof predictions_suggestions;
  "predictions/types": typeof predictions_types;
  predictions: typeof predictions;
  predictions7Day: typeof predictions7Day;
  predictionsAtRisk: typeof predictionsAtRisk;
  quickFix: typeof quickFix;
  recalculateAllHabitsStrength: typeof recalculateAllHabitsStrength;
  "reflections/index": typeof reflections_index;
  "reflections/types": typeof reflections_types;
  reflections: typeof reflections;
  reflectionsMutations: typeof reflectionsMutations;
  reflectionsQueries: typeof reflectionsQueries;
  router: typeof router;
  "settings/normalizers": typeof settings_normalizers;
  "settings/settings": typeof settings_settings;
  "settings/types": typeof settings_types;
  "settings/validators": typeof settings_validators;
  settings: typeof settings;
  storage: typeof storage;
  "streakUtils/dateHelpers": typeof streakUtils_dateHelpers;
  "streakUtils/historyCalculation": typeof streakUtils_historyCalculation;
  "streakUtils/index": typeof streakUtils_index;
  "streakUtils/types": typeof streakUtils_types;
  "streakUtils/updateStreak": typeof streakUtils_updateStreak;
  streakUtils: typeof streakUtils;
  "subscriptions/helpers": typeof subscriptions_helpers;
  subscriptions: typeof subscriptions;
  "templates/clearAndDedupe": typeof templates_clearAndDedupe;
  "templates/helpers": typeof templates_helpers;
  "templates/importTemplate": typeof templates_importTemplate;
  "templates/queries": typeof templates_queries;
  "templates/types": typeof templates_types;
  "templates/updateLinks": typeof templates_updateLinks;
  templates: typeof templates;
  templatesDataSeed: typeof templatesDataSeed;
  testStrength: typeof testStrength;
  "tracking/getCompletionStatus": typeof tracking_getCompletionStatus;
  "tracking/helpers": typeof tracking_helpers;
  "tracking/index": typeof tracking_index;
  "tracking/strengthUpdater": typeof tracking_strengthUpdater;
  tracking: typeof tracking;
  users: typeof users;
  visionBoard: typeof visionBoard;
  "visionBoardImages/constants": typeof visionBoardImages_constants;
  "visionBoardImages/helpers": typeof visionBoardImages_helpers;
  "visionBoardImages/index": typeof visionBoardImages_index;
  "visionBoardImages/validators": typeof visionBoardImages_validators;
  visionBoardImages: typeof visionBoardImages;
  visionBoardImagesCreate: typeof visionBoardImagesCreate;
  visionBoardImagesDelete: typeof visionBoardImagesDelete;
  visionBoardImagesMutations: typeof visionBoardImagesMutations;
  visionBoardImagesQueries: typeof visionBoardImagesQueries;
  "voiceNotes/index": typeof voiceNotes_index;
  "voiceNotes/streakHelpers": typeof voiceNotes_streakHelpers;
  "voiceNotes/types": typeof voiceNotes_types;
  voiceNotes: typeof voiceNotes;
  voiceNotesMutations: typeof voiceNotesMutations;
  voiceNotesQueries: typeof voiceNotesQueries;
  voiceNotesStreakQuery: typeof voiceNotesStreakQuery;
  "webhooks/revenuecat": typeof webhooks_revenuecat;
  "webhooks/revenuecatSignature": typeof webhooks_revenuecatSignature;
}>;
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;
