/**
 * Onboarding / starter habits that stay free so a new user can
 * browse every category and import a first set without paying.
 */
export const FREE_STARTER_TEMPLATE_NAMES: readonly string[] = [
  '5-Minute Meditation',
  'Hydration First',
  'Make Your Bed',
  'Morning Pages',
  'Consistent Wake Time',
  'Gratitude Journaling',
  'Daily Reading',
  'Daily Learning',
  'Pomodoro Technique',
  '10,000 Steps',
  '7,000 Steps',
  'Stretching Routine',
  '7-Minute Workout',
  'Box Breathing',
  'Digital Detox Hour',
  'Consistent Bedtime',
  'No Screens Before Bed',
  'Expense Tracking',
  'Daily Social Call',
  'Express Gratitude',
  'Phone-Free Meals',
  'Phone-Free First Hour',
  'Evening Planning',
  'Daily Declutter',
  'Morning Mirror Smile',
  'Daily Flossing',
  'Post-Meal Walk',
  'Two-Minute Tidy',
  'Daily Top 3 Priorities',
  'Work Breaks',
  'Walking in Nature',
  '4-7-8 Breathing',
  'Automatic Savings',
  'Daily Sketching',
  'Morning Freewriting',
  'Random Act of Kindness',
  'Cold Shower',
  'Sunrise Viewing',
  'No Added Sugar',
];
