/**
 * Seed Marketplace Templates
 * Curated collections of habit templates for the Templates Marketplace
 */

import { v } from 'convex/values';
import { mutation } from '../_generated/server';

/**
 * Mutation: Seed marketplace templates
 */
export const seedMarketplaceTemplates = mutation({
  args: {},
  handler: async (ctx) => {
    const now = Date.now();

    // === Fitness Collection ===
    await ctx.db.insert('templates', {
      name: 'Morning Fitness Starter',
      category: 'health_fitness',
      description: 'Build a morning fitness habit with simple exercises you can do at home',
      frequency: 'daily',
      icon: '💪',
      iconColor: '#10B981',
      scientificReference: 'Lally et al. (2010) - 66 days average to form habit',
      tips: ['Start with 10 minutes', 'Do it right after waking up', 'Progress slowly'],
      createdAt: now,
      difficulty: 'easy',
      estimatedTime: 15,
      featured: true,
      isMarketplaceTemplate: true,
      collections: ['beginner_friendly', 'quick_wins'],
      averageRating: 4.5,
      ratingCount: 127,
      habits: [
        {
          name: 'Morning Stretching',
          description: '5 minutes of light stretching to wake up your body',
          frequency: 'daily',
          icon: '🧘',
          iconColor: '#8B5CF6',
          cueTime: '7:00 AM',
          tips: ['Focus on major muscle groups', 'Listen to your body'],
          why: 'Reduces injury risk and improves flexibility',
        },
        {
          name: 'Push-ups',
          description: 'Build upper body strength with push-ups',
          frequency: 'daily',
          icon: '💪',
          iconColor: '#EF4444',
          cueAfterBehavior: 'morning stretching',
          tips: ['Start with modified push-ups if needed', 'Keep core tight'],
          why: 'Builds chest, shoulders, and triceps',
        },
      ],
    });

    await ctx.db.insert('templates', {
      name: 'Summer Fitness Challenge',
      category: 'health_fitness',
      description: 'Get in shape for summer with this 30-day fitness program',
      frequency: 'daily',
      icon: '☀️',
      iconColor: '#F59E0B',
      scientificReference: 'American Council on Exercise (ACE)',
      tips: ['Stay hydrated', 'Listen to your body', 'Rest when needed'],
      createdAt: now,
      difficulty: 'medium',
      estimatedTime: 45,
      featured: true,
      seasonalCollection: 'summer',
      isMarketplaceTemplate: true,
      collections: ['seasonal', 'challenge'],
      averageRating: 4.7,
      ratingCount: 89,
      habits: [
        {
          name: 'Morning Run',
          description: 'Start your day with a refreshing run',
          frequency: 'daily',
          icon: '🏃',
          iconColor: '#10B981',
          cueTime: '6:30 AM',
          tips: ['Start with walking intervals', 'Find a scenic route'],
          why: 'Builds cardiovascular endurance and burns calories',
        },
        {
          name: 'Strength Training',
          description: 'Build muscle with bodyweight exercises',
          frequency: 'daily',
          icon: '💪',
          iconColor: '#EF4444',
          cueAfterBehavior: 'morning run',
          tips: ['Focus on form over speed', 'Rest between sets'],
          why: 'Increases metabolism and builds lean muscle',
        },
        {
          name: 'Afternoon Walk',
          description: 'Take a 30-minute walk to stay active',
          frequency: 'daily',
          icon: '🚶',
          iconColor: '#3B82F6',
          cueTime: '2:00 PM',
          tips: ['Find a walking buddy', 'Listen to a podcast'],
          why: 'Reduces stress and improves digestion',
        },
      ],
    });

    await ctx.db.insert('templates', {
      name: 'HIIT Intervals',
      category: 'health_fitness',
      description: 'High-intensity interval training for maximum calorie burn',
      frequency: 'daily',
      icon: '🔥',
      iconColor: '#EF4444',
      scientificReference: 'Gibala et al. (2012) - HIIT benefits',
      tips: ['Warm up first', 'Give 100% effort during intervals', 'Cool down after'],
      createdAt: now,
      difficulty: 'hard',
      estimatedTime: 30,
      isMarketplaceTemplate: true,
      collections: ['advanced', 'time_efficient'],
      averageRating: 4.3,
      ratingCount: 54,
      habits: [
        {
          name: 'Tabata Sprint Intervals',
          description: '20 seconds work, 10 seconds rest, 8 rounds',
          frequency: 'daily',
          icon: '🔥',
          iconColor: '#EF4444',
          cueTime: '7:00 AM',
          tips: ['Sprint at maximum intensity', 'Rest completely'],
          why: 'Maximizes calorie burn in minimal time',
        },
        {
          name: 'Burpee Sets',
          description: '3 sets of 15 burpees with rest periods',
          frequency: 'daily',
          icon: '💪',
          iconColor: '#10B981',
          cueAfterBehavior: 'Tabata Sprint Intervals',
          tips: ['Maintain proper form', 'Modify if needed'],
          why: 'Full body conditioning exercise',
        },
      ],
    });

    // === Mindfulness Collection ===
    await ctx.db.insert('templates', {
      name: 'Morning Mindfulness Routine',
      category: 'mindfulness',
      description: 'Start your day with clarity and calm through simple mindfulness practices',
      frequency: 'daily',
      icon: '🧘',
      iconColor: '#8B5CF6',
      scientificReference: 'Kabat-Zinn (2003) - Mindfulness-based stress reduction',
      tips: ['Be consistent with timing', 'Start with just 5 minutes', 'Don\'t judge your thoughts'],
      createdAt: now,
      difficulty: 'easy',
      estimatedTime: 20,
      featured: true,
      isMarketplaceTemplate: true,
      collections: ['beginner_friendly', 'stress_reduction'],
      averageRating: 4.8,
      ratingCount: 203,
      habits: [
        {
          name: 'Morning Meditation',
          description: '10 minutes of guided meditation to start your day',
          frequency: 'daily',
          icon: '🧘',
          iconColor: '#8B5CF6',
          cueTime: '7:00 AM',
          cueLocation: 'Quiet corner',
          tips: ['Use a guided meditation app', 'Focus on your breath'],
          identity: 'I am a mindful person who starts each day with intention',
          why: 'Reduces stress and improves focus throughout the day',
        },
        {
          name: 'Gratitude Journal',
          description: 'Write 3 things you\'re grateful for',
          frequency: 'daily',
          icon: '📝',
          iconColor: '#F59E0B',
          cueAfterBehavior: 'Morning Meditation',
          tips: ['Be specific', 'Include small things', 'Review at end of day'],
          identity: 'I am someone who notices and appreciates the good in life',
          why: 'Increases happiness and life satisfaction',
        },
      ],
    });

    await ctx.db.insert('templates', {
      name: 'Stress Relief Bundle',
      category: 'mindfulness',
      description: 'Manage stress and anxiety with daily mindfulness practices',
      frequency: 'daily',
      icon: '😌',
      iconColor: '#3B82F6',
      scientificReference: 'Hofmann et al. (2010) - Mindfulness meta-analysis',
      tips: ['Practice during stressful moments', 'Be patient with yourself', 'Track your progress'],
      createdAt: now,
      difficulty: 'medium',
      estimatedTime: 35,
      isMarketplaceTemplate: true,
      collections: ['mental_health', 'stress_management'],
      averageRating: 4.6,
      ratingCount: 142,
      habits: [
        {
          name: 'Deep Breathing',
          description: '5 minutes of deep breathing exercises',
          frequency: 'daily',
          icon: '🌬️',
          iconColor: '#10B981',
          cueTime: '9:00 AM',
          tips: ['Breathe from diaphragm', 'Count to 4 on inhale, 6 on exhale'],
          why: 'Activates parasympathetic nervous system',
        },
        {
          name: 'Body Scan',
          description: 'Progressive muscle relaxation technique',
          frequency: 'daily',
          icon: '🧘',
          iconColor: '#8B5CF6',
          cueTime: '9:00 PM',
          cueLocation: 'Bed',
          tips: ['Start from toes and work up', 'Tense then release each muscle group'],
          why: 'Reduces physical tension and improves sleep',
        },
        {
          name: 'Mindful Walk',
          description: 'Walk with full awareness of your surroundings',
          frequency: 'daily',
          icon: '🚶',
          iconColor: '#3B82F6',
          cueTime: '12:00 PM',
          tips: ['Notice sights, sounds, smells', 'Walk slowly', 'Leave phone behind'],
          why: 'Grounds you in present moment',
        },
      ],
    });

    // === Productivity Collection ===
    await ctx.db.insert('templates', {
      name: 'Productivity Powerhouse',
      category: 'productivity',
      description: 'Boost your productivity with science-backed habits',
      frequency: 'daily',
      icon: '🚀',
      iconColor: '#3B82F6',
      scientificReference: 'Covey (1989) - The 7 Habits of Highly Effective People',
      tips: ['Start with most important task', 'Take breaks', 'Review daily'],
      createdAt: now,
      difficulty: 'medium',
      estimatedTime: 60,
      featured: true,
      isMarketplaceTemplate: true,
      collections: ['efficiency', 'goal_achievement'],
      averageRating: 4.5,
      ratingCount: 176,
      habits: [
        {
          name: 'Morning Planning',
          description: 'Plan your top 3 priorities for the day',
          frequency: 'daily',
          icon: '📋',
          iconColor: '#3B82F6',
          cueTime: '8:00 AM',
          tips: ['Write them down', 'Be specific', 'Time-block your calendar'],
          identity: 'I am a person who plans and executes with purpose',
          why: 'Ensures focus on what matters most',
        },
        {
          name: 'Deep Work Session',
          description: '90 minutes of focused, distraction-free work',
          frequency: 'daily',
          icon: '🎯',
          iconColor: '#EF4444',
          cueTime: '9:00 AM',
          cueLocation: 'Desk',
          tips: ['Put phone away', 'Close unnecessary tabs', 'Use noise-canceling headphones'],
          identity: 'I am a person who produces quality work through deep focus',
          why: 'Maximizes productivity on important tasks',
        },
        {
          name: 'Evening Review',
          description: 'Review accomplishments and plan tomorrow',
          frequency: 'daily',
          icon: '📝',
          iconColor: '#F59E0B',
          cueTime: '8:00 PM',
          tips: ['Celebrate wins', 'Identify blockers', 'Leave a clear starting point'],
          identity: 'I am someone who learns and improves every day',
          why: 'Creates momentum and prevents morning indecision',
        },
      ],
    });

    await ctx.db.insert('templates', {
      name: 'Study Season Survival',
      category: 'productivity',
      description: 'Academic success habits for students and learners',
      frequency: 'daily',
      icon: '📚',
      iconColor: '#8B5CF6',
      scientificReference: 'Dunlosky et al. (2013) - Effective study techniques',
      tips: ['Spaced repetition is key', 'Active recall beats passive reading', 'Take regular breaks'],
      createdAt: now,
      difficulty: 'medium',
      estimatedTime: 90,
      seasonalCollection: 'study',
      isMarketplaceTemplate: true,
      collections: ['student', 'learning'],
      averageRating: 4.4,
      ratingCount: 98,
      habits: [
        {
          name: 'Daily Review',
          description: 'Review notes from yesterday\'s classes',
          frequency: 'daily',
          icon: '📖',
          iconColor: '#3B82F6',
          cueTime: '8:00 AM',
          tips: ['Use active recall', 'Teach concepts to yourself', 'Make connections'],
          why: 'Strengthens memory and understanding',
        },
        {
          name: 'Pomodoro Study',
          description: '4 pomodoros (25 min work, 5 min break) with longer break after',
          frequency: 'daily',
          icon: '🍅',
          iconColor: '#EF4444',
          cueTime: '10:00 AM',
          cueLocation: 'Library or study space',
          tips: ['One task per pomodoro', 'Stand during breaks', 'Track completed pomodoros'],
          identity: 'I am a dedicated learner who masters material through consistent effort',
          why: 'Prevents burnout and maintains focus',
        },
        {
          name: 'Flashcard Review',
          description: 'Review flashcards with spaced repetition',
          frequency: 'daily',
          icon: '🃏',
          iconColor: '#F59E0B',
          cueTime: '6:00 PM',
          tips: ['Use Anki or similar app', 'Review difficult cards more often', 'Create your own cards'],
          why: 'Maximizes retention with minimal time',
        },
      ],
    });

    // === Health Collection ===
    await ctx.db.insert('templates', {
      name: 'Health Foundation',
      category: 'health_fitness',
      description: 'Build the foundation of good health with essential habits',
      frequency: 'daily',
      icon: '❤️',
      iconColor: '#EF4444',
      scientificReference: 'World Health Organization health guidelines',
      tips: ['Start small', 'Build one habit at a time', 'Track progress'],
      createdAt: now,
      difficulty: 'easy',
      estimatedTime: 30,
      featured: true,
      isMarketplaceTemplate: true,
      collections: ['beginner_friendly', 'essential'],
      averageRating: 4.7,
      ratingCount: 234,
      habits: [
        {
          name: 'Drink Water First Thing',
          description: 'Drink a full glass of water immediately upon waking',
          frequency: 'daily',
          icon: '💧',
          iconColor: '#3B82F6',
          cueTime: '7:00 AM',
          cueLocation: 'Kitchen',
          tips: ['Keep water by your bed', 'Add lemon for flavor', 'Use a marked bottle'],
          identity: 'I am someone who nourishes my body from the moment I wake',
          why: 'Rehydrates after sleep and kickstarts metabolism',
        },
        {
          name: 'Take Vitamins',
          description: 'Take your daily vitamins and supplements',
          frequency: 'daily',
          icon: '💊',
          iconColor: '#10B981',
          cueAfterBehavior: 'Drink Water First Thing',
          tips: ['Set a phone reminder', 'Keep visible container', 'Track streak'],
          why: 'Ensures essential nutrients',
        },
        {
          name: 'Fruit or Veggie',
          description: 'Eat at least one serving of fruit or vegetables',
          frequency: 'daily',
          icon: '🥦',
          iconColor: '#10B981',
          cueTime: '12:00 PM',
          tips: ['Add to every meal', 'Keep healthy snacks visible', 'Try new varieties'],
          identity: 'I am someone who fuels my body with nutritious foods',
          why: 'Provides essential vitamins and fiber',
        },
      ],
    });

    // === New Year Resolution Collection ===
    await ctx.db.insert('templates', {
      name: 'New Year, New You',
      category: 'productivity',
      description: 'Transform your life with this comprehensive 30-day resolution program',
      frequency: 'daily',
      icon: '🎉',
      iconColor: '#F59E0B',
      scientificReference: 'Norcross et al. (2002) - Resolution success factors',
      tips: ['Start before January 1st', 'Tell friends for accountability', 'Track daily'],
      createdAt: now,
      difficulty: 'hard',
      estimatedTime: 90,
      featured: true,
      seasonalCollection: 'new_year',
      isMarketplaceTemplate: true,
      collections: ['transformation', 'resolution'],
      averageRating: 4.4,
      ratingCount: 156,
      habits: [
        {
          name: 'Morning Exercise',
          description: '30 minutes of exercise every morning',
          frequency: 'daily',
          icon: '🏃',
          iconColor: '#10B981',
          cueTime: '6:30 AM',
          tips: ['Vary your activities', 'Find what you enjoy', 'Prepare clothes night before'],
          identity: 'I am an active, energetic person who moves my body daily',
          why: 'Boosts energy, mood, and overall health',
        },
        {
          name: 'Healthy Breakfast',
          description: 'Prepare and eat a nutritious breakfast',
          frequency: 'daily',
          icon: '🍳',
          iconColor: '#F59E0B',
          cueAfterBehavior: 'Morning Exercise',
          tips: ['Meal prep on weekends', 'Include protein', 'Limit sugar'],
          identity: 'I nourish my body with healthy, energizing food',
          why: 'Sets healthy tone for entire day',
        },
        {
          name: 'No Screens After 9 PM',
          description: 'Put away all electronic devices by 9 PM',
          frequency: 'daily',
          icon: '📱',
          iconColor: '#8B5CF6',
          cueTime: '9:00 PM',
          tips: ['Use physical alarm clock', 'Keep phone in other room', 'Read instead'],
          identity: 'I prioritize rest and mental clarity over digital distraction',
          why: 'Improves sleep quality and reduces stress',
        },
        {
          name: 'Read 10 Pages',
          description: 'Read for personal growth daily',
          frequency: 'daily',
          icon: '📚',
          iconColor: '#3B82F6',
          cueAfterBehavior: 'No Screens After 9 PM',
          tips: ['Keep book by bed', 'Choose inspiring content', 'Track pages read'],
          identity: 'I am a continuous learner who expands my mind daily',
          why: 'Builds knowledge and perspective',
        },
      ],
    });

    return { success: true, seeded: 9 };
  },
});
