/**
 * Curated premium template names. Starter / onboarding habits stay free
 * via `FREE_STARTER_TEMPLATE_NAMES` in premiumFlags.ts.
 */
export const PREMIUM_TEMPLATE_NAMES: readonly string[] = [
  // Huberman-protocol pack
  'Morning Sunlight Viewing',
  'Delay Caffeine 90 Minutes',
  'Zone 2 Cardio Training',
  'Deliberate Cold Exposure',
  'NSDR Practice',
  'Physiological Sigh',
  'Evening Light Dimming',
  'Cool Sleep Temperature',
  'Morning Protein Protocol',
  'Time-Restricted Eating',
  '16:8 Intermittent Fasting',
  'Sauna Therapy',
  'Sleep Optimization',
  'Darkness Before Sleep',
  'Optimal Sleep Temperature',
  // Longevity / advanced fitness
  'VO2 Max Training',
  'Grip Strength Training',
  'Floor Sitting Practice',
  'Single-Leg Balance Test',
  'Muscle Preservation',
  'Ground Transitions',
  'Resting Heart Rate Check',
  'Isometric Wall Sit',
  'Daily Hanging',
  'Balance Training',
  'Heat Therapy Bath',
  'Barefoot Grounding',
  'Bone-Strengthening Exercise',
  'Joint Mobility Routine',
  'Always Take Stairs',
  'Brisk Walking Pace',
  'Protein Per Meal Goal',
  'Exercise Snacks (Stair Climbs)',
  '5-Minute Mobility Snack',
  'Daily Nuts Serving',
  // Specialized mental health
  'Cognitive Defusion',
  'Behavioral Activation',
  'Values Clarification',
  'Emotion Granularity',
  'Opposite Action',
  'Self-Distancing',
  'Expressive Writing',
  'Self-Compassion Break',
  'Dual N-Back Training',
  'Dopamine Reset',
  '13-Minute Focus Meditation',
  'Scheduled Worry Time',
  // Recovery / biohacking
  'Red Light Therapy',
  'Sauna Recovery',
  'Yoga Nidra/NSDR',
  'Mouth Taping Sleep',
  'Wim Hof Breathing',
  'CO2 Tolerance Training',
  'Evening Magnesium',
  'Weighted Blanket Sleep',
  'Contrast Shower',
  'Evening Sunset Viewing',
  'Power Nap',
  'Daily Humming',
  'Energizing Breath (Kapalabhati)',
  'Resonant Breathing',
  'Sleep Sound Machine',
  // Nutrition science
  'Pre-Meal Vinegar',
  'Resistant Starch',
  'Protein Pacing',
  '30 Plants Per Week',
  'Daily Fermented Foods',
  'Omega-3 Rich Foods',
  'Mediterranean Plate',
  'Protein Per Meal (25–30g)',
  'Eat Greens First',
  'No Late Night Eating',
  // Advanced social
  'Love Maps Question',
  'Six-Second Kiss',
  'Stress-Reducing Conversation',
  'Active Constructive Responding',
  'Vulnerability Practice',
  'Eye Contact Practice',
  'Reflective Listening',
  'Weekly Date Night',
  // Advanced learning / career
  'Interleaved Practice',
  'Bilateral Eye Movements',
  'Same-Day Review',
  'Career Documentation',
  'Professional Networking',
  'Public Speaking Practice',
  'Deliberate Skill Practice',
  'Novel Learning Session',
  'Weekly Networking Outreach',
  'Language Word Learning',
];
