import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  addButton: {
    alignItems: 'center',
    backgroundColor: '#059669',
    borderRadius: 24,
    elevation: 6,
    height: 48,
    justifyContent: 'center',
    marginTop: -16,
    shadowColor: '#2D2A26',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    width: 48,
  },
  addButtonDark: { elevation: 8, shadowColor: '#059669', shadowOpacity: 0.4 },
  addBorderDark: { borderColor: 'rgba(23,23,23,0.97)', borderWidth: 3 },
  addBorderLight: { borderColor: 'rgba(255,255,255,0.97)', borderWidth: 3 },
  badgeDot: {
    backgroundColor: '#ef4444',
    borderRadius: 5,
    borderWidth: 2,
    height: 10,
    position: 'absolute',
    right: -3,
    top: -3,
    width: 10,
    zIndex: 5,
  },
  badgeDotBorderDark: { borderColor: 'rgba(23,23,23,0.97)' },
  badgeDotBorderLight: { borderColor: 'rgba(255,255,255,0.97)' },
  centerZone: {
    alignItems: 'center',
    flex: 1,
    justifyContent: 'center',
    overflow: 'visible',
  },
  container: {
    alignItems: 'center',
    borderTopWidth: 1,
    flexDirection: 'row',
    overflow: 'visible',
    paddingHorizontal: 16,
    paddingTop: 10,
  },
  containerBorderDark: { borderTopColor: '#2a2a2a' },
  containerBorderLight: { borderTopColor: '#f0eeee' },
  leftZone: { alignItems: 'flex-start', flex: 1 },
  rightZone: { alignItems: 'flex-end', flex: 1 },
  settingsButton: {
    alignItems: 'center',
    borderRadius: 10,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 5,
    height: 36,
    justifyContent: 'center',
    minWidth: 108,
    paddingHorizontal: 10,
  },
  settingsDark: {
    backgroundColor: 'rgba(31,41,55,0.6)',
    borderColor: '#374151',
  },
  settingsLabel: { fontSize: 12, fontWeight: '600' },
  settingsLabelDark: { color: '#9ca3af' },
  settingsLabelLight: { color: '#44403c' },
  settingsLight: { backgroundColor: 'transparent', borderColor: '#e7e5e4' },
  templatesButton: {
    alignItems: 'center',
    backgroundColor: '#7c3aed',
    borderRadius: 10,
    flexDirection: 'row',
    gap: 5,
    height: 36,
    justifyContent: 'center',
    minWidth: 108,
    paddingHorizontal: 10,
  },
  templatesLabel: { color: '#ffffff', fontSize: 12, fontWeight: '600' },
  templatesWrapper: { position: 'relative' },
});
